export const data = [
	{
		categories: [ 'Solar system', 'Satellite', 'Earth', 'Moon' ],
		date: '2021-01-01',
		datetime: '2021-01-01T14:30:00Z',
		email: 'moon@example.com',
		id: 1,
		image: 'https://live.staticflickr.com/7398/9458193857_e1256123e3_z.jpg',
		isPlanet: false,
		name: {
			description:
				"The Moon is Earth's only natural satellite, orbiting at an average distance of 384,400 kilometers with a synchronous rotation that leads to fixed lunar phases as seen from Earth. Its cratered surface and subtle glow define night skies, inspiring exploration missions and influencing tides and biological rhythms worldwide.",
			title: 'Moon',
		},
		satellites: 0,
		type: 'Satellite',
	},
	{
		categories: [ 'Solar system', 'Satellite', 'Jupiter', 'Moon' ],
		date: '2019-01-02',
		datetime: '2019-01-02T09:15:00Z',
		email: 'io@example.com',
		id: 2,
		image: 'https://live.staticflickr.com/5482/9460973502_07e8ab81fe_z.jpg',
		isPlanet: false,
		name: {
			description: 'Moon of Jupiter',
			title: 'Io',
		},
		satellites: 0,
		type: 'Satellite',
	},
	{
		categories: [ 'Solar system', 'Satellite', 'Jupiter', 'Moon' ],
		date: '2025-01-03',
		datetime: '2025-01-03T16:45:30Z',
		email: 'europa@example.com',
		id: 3,
		image: 'https://live.staticflickr.com/65535/31499273012_baf5f38cc1_z.jpg',
		isPlanet: false,
		name: {
			description: 'Moon of Jupiter',
			title: 'Europa',
		},
		satellites: 0,
		type: 'Satellite',
	},
	{
		categories: [ 'Solar system', 'Satellite', 'Jupiter', 'Moon' ],
		date: '2022-01-04',
		datetime: '2022-01-04T12:30:00Z',
		email: 'ganymede@example.com',
		id: 4,
		image: 'https://live.staticflickr.com/7816/33436473218_a836235935_k.jpg',
		isPlanet: false,
		name: {
			description: 'Largest moon of Jupiter',
			title: 'Ganymede',
		},
		satellites: 0,
		type: 'Satellite',
	},
	{
		categories: [ 'Solar system', 'Satellite', 'Jupiter', 'Moon' ],
		date: '2021-01-05',
		datetime: '2021-01-05T14:15:30Z',
		email: 'callisto@example.com',
		id: 5,
		image: 'https://live.staticflickr.com/804/27604150528_4512448a9c_c.jpg',
		isPlanet: false,
		name: {
			description: 'Outermost Galilean moon of Jupiter',
			title: 'Callisto',
		},
		satellites: 0,
		type: 'Satellite',
	},
	{
		categories: [ 'Solar system', 'Satellite', 'Jupiter', 'Moon' ],
		date: '2020-01-06',
		datetime: '2020-01-06T10:45:15Z',
		email: 'amalthea@example.com',
		id: 6,
		image: 'https://upload.wikimedia.org/wikipedia/commons/6/62/Amalthea.gif',
		isPlanet: false,
		name: {
			description: 'Small irregular moon of Jupiter',
			title: 'Amalthea',
		},
		satellites: 0,
		type: 'Satellite',
	},
	{
		categories: [ 'Solar system', 'Satellite', 'Jupiter', 'Moon' ],
		date: '2019-01-07',
		datetime: '2019-01-07T16:20:45Z',
		email: 'himalia@example.com',
		id: 7,
		image: 'https://upload.wikimedia.org/wikipedia/commons/c/c2/Cassini-Huygens_Image_of_Himalia.png',
		isPlanet: false,
		name: {
			description: 'Largest irregular moon of Jupiter',
			title: 'Himalia',
		},
		satellites: 0,
		type: 'Satellite',
	},
	{
		categories: [ 'Ice giant', 'Planet', 'Solar system' ],
		date: '2020-01-01',
		datetime: '2020-01-01T11:22:15Z',
		email: 'neptune@example.com',
		id: 8,
		image: 'https://live.staticflickr.com/65535/29523683990_000ff4720c_z.jpg',
		isPlanet: true,
		name: {
			description: 'Ice giant in the Solar system',
			title: 'Neptune',
		},
		satellites: 16,
		type: 'Ice giant',
	},
	{
		categories: [ 'Solar system', 'Satellite', 'Neptune', 'Moon' ],
		date: '2021-02-01',
		datetime: '2021-02-01T11:30:00Z',
		email: 'triton@example.com',
		id: 9,
		image: 'https://live.staticflickr.com/65535/50728384241_02c5126c30_h.jpg',
		isPlanet: false,
		name: {
			description: 'Largest moon of Neptune',
			title: 'Triton',
		},
		satellites: 0,
		type: 'Satellite',
	},
	{
		categories: [ 'Solar system', 'Satellite', 'Neptune', 'Moon' ],
		date: '2020-02-02',
		datetime: '2020-02-02T15:45:30Z',
		email: 'nereid@example.com',
		id: 10,
		image: 'https://upload.wikimedia.org/wikipedia/commons/b/b0/Nereid-Voyager2.jpg',
		isPlanet: false,
		name: {
			description: 'Irregular moon of Neptune',
			title: 'Nereid',
		},
		satellites: 0,
		type: 'Satellite',
	},
];
